# Generated by Django 6.0.4 on 2026-04-17 13:07

from django.db import migrations


def forwards(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    for user in User.objects.all().iterator():
        if Profile.objects.filter(user_id=user.pk).exists():
            continue
        role = "landlord" if user.username == "demo_landlord" else "renter"
        Profile.objects.create(user=user, role=role)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
