# Generated by Django 6.0.4 on 2026-04-17 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='назва')),
                ('description', models.TextField(verbose_name='опис')),
                ('address_or_district', models.CharField(max_length=300, verbose_name='адреса або район')),
                ('city', models.CharField(max_length=120, verbose_name='місто')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ціна')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='кількість кімнат')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='площа, м²')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='поверх')),
                ('housing_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Будинок'), ('room', 'Кімната'), ('studio', 'Студія')], default='apartment', max_length=20, verbose_name='тип житла')),
                ('has_furniture', models.BooleanField(default=False, verbose_name='наявність меблів')),
                ('has_appliances', models.BooleanField(default=False, verbose_name='наявність техніки')),
                ('contact_info', models.CharField(max_length=500, verbose_name='контактна інформація')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На модерації'), ('published', 'Опубліковано'), ('rejected', 'Відхилено')], default='draft', max_length=20, verbose_name='статус оголошення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/', verbose_name='фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='listings_li_status_f5055b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_e45c53_idx'),
        ),
    ]
