# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingimage",
            name="external_url",
            field=models.URLField(
                blank=True,
                max_length=2048,
                verbose_name="посилання на фото",
            ),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listings/%Y/%m/",
                verbose_name="фото",
            ),
        ),
    ]
